import type { Metadata } from "next";
import { LegalSection } from "@/components/legal/LegalSection";
import { CONTACT_EMAIL, GOVERNING_LAW } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Terms of Use",
  description:
    "OsuStocks is a free, fan-made game. All currency and holdings are virtual, with no real money and no payouts.",
};

const LAST_UPDATED = "June 7, 2026";
const API_REPO = "https://github.com/zidanejidan12/OsuStocks.API";

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:py-16">
      <p className="text-[11px] font-medium uppercase tracking-[0.12em] text-zinc-500">
        Legal
      </p>
      <h1 className="mt-2 text-3xl font-semibold tracking-tighter sm:text-4xl">
        Terms of Use
      </h1>
      <p className="mt-2 text-sm text-zinc-500">Last updated: {LAST_UPDATED}</p>

      <div className="mt-8 rounded-2xl border border-pink-500/30 bg-pink-500/10 p-5">
        <div className="flex items-start gap-3">
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
            className="mt-0.5 h-5 w-5 shrink-0 text-pink-300"
          >
            <path d="M10.3 3.6 1.8 18a2 2 0 0 0 1.7 3h16.9a2 2 0 0 0 1.7-3L13.7 3.6a2 2 0 0 0-3.4 0Z" />
            <path d="M12 9v4" />
            <path d="M12 17h.01" />
          </svg>
          <p className="text-sm leading-relaxed text-pink-50/90">
            <strong className="font-semibold text-pink-100">
              OsuStocks is a game.
            </strong>{" "}
            The coins, prices, shares, and portfolio values are entirely virtual
            and have <strong className="text-pink-100">no real-world monetary
            value</strong>. You cannot buy, sell, deposit, withdraw, or redeem
            them for money or anything of value. OsuStocks is not investing,
            trading, financial advice, or gambling. It is entertainment.
          </p>
        </div>
      </div>

      <div className="mt-10 space-y-9">
        <LegalSection title="1. Acceptance of these terms">
          <p>
            By accessing or using OsuStocks (the &ldquo;Service&rdquo;), you agree
            to these Terms of Use and our{" "}
            <a href="/privacy">Privacy Policy</a>. If you do not agree, please do
            not use the Service.
          </p>
        </LegalSection>

        <LegalSection title="2. What OsuStocks is">
          <p>
            OsuStocks is a free, fan-made browser game that simulates a stock
            market using the public performance statistics of osu! players. You
            use a virtual balance to &ldquo;buy&rdquo; and &ldquo;sell&rdquo;
            virtual shares and track a virtual portfolio. It exists purely for fun
            and entertainment.
          </p>
        </LegalSection>

        <LegalSection title="3. No real money and no financial product">
          <p>
            Every in-game item, including coins, balances, prices, shares,
            holdings, and profit or loss, is virtual and fictional. These items have
            no monetary or real-world value and cannot be purchased, cashed out,
            transferred, traded for goods or services, or redeemed for anything.
          </p>
          <p>
            OsuStocks does not process real payments and is{" "}
            <strong>
              not a financial product, broker, exchange, investment service, or
              gambling service
            </strong>
            . Nothing in the Service is financial advice. Prices are generated by
            the game and do not represent any real market or asset.
          </p>
        </LegalSection>

        <LegalSection title="4. Not affiliated with osu!">
          <p>
            OsuStocks is an independent fan project. It is{" "}
            <strong>
              not created, endorsed, sponsored by, or affiliated with osu!, ppy
              Pty Ltd, or any player
            </strong>{" "}
            featured in the game. &ldquo;osu!&rdquo; and related names and logos
            are the property of their respective owners. Player names and
            statistics are used only to power the game&rsquo;s simulation.
          </p>
        </LegalSection>

        <LegalSection title="5. Your osu! account">
          <p>
            You sign in using osu!&rsquo;s OAuth. You are responsible for activity
            under your account and for keeping your access token private. Do not
            share your token, attempt to access other people&rsquo;s accounts, or
            impersonate others.
          </p>
        </LegalSection>

        <LegalSection title="6. Acceptable use">
          <p>You agree not to:</p>
          <ul>
            <li>use bots, scripts, or automation to play or query the Service;</li>
            <li>
              exploit bugs, or attempt to manipulate balances, prices, or the
              simulated market unfairly;
            </li>
            <li>
              access or interfere with accounts or data that are not your own;
            </li>
            <li>
              disrupt, overload, or attack the Service or its underlying API;
            </li>
            <li>use the Service for any unlawful purpose.</li>
          </ul>
        </LegalSection>

        <LegalSection title="7. Virtual balances may change or reset">
          <p>
            Because nothing in the game has real value, we may add, change,
            remove, recalculate, or reset any virtual balances, prices, players,
            or game rules at any time, and may suspend or discontinue the Service,
            without notice and without liability to you.
          </p>
        </LegalSection>

        <LegalSection title="8. Provided &ldquo;as is&rdquo;">
          <p>
            The Service is provided &ldquo;as is&rdquo; and &ldquo;as
            available,&rdquo; without warranties of any kind, express or implied.
            We do not guarantee that it will be accurate, uninterrupted, secure,
            or error-free.
          </p>
        </LegalSection>

        <LegalSection title="9. Limitation of liability">
          <p>
            To the maximum extent permitted by law, the operators of OsuStocks
            will not be liable for any indirect, incidental, or consequential
            damages arising from your use of, or inability to use, the Service.
            Because the Service involves no real money or value, you acknowledge
            there is no monetary loss associated with any virtual item.
          </p>
        </LegalSection>

        <LegalSection title="10. Changes to these terms">
          <p>
            We may update these Terms from time to time. Material changes will be
            reflected by the &ldquo;Last updated&rdquo; date above. Your continued
            use of the Service after changes take effect means you accept the
            updated Terms.
          </p>
        </LegalSection>

        {GOVERNING_LAW && (
          <LegalSection title="11. Governing law">
            <p>
              These Terms are governed by the laws of {GOVERNING_LAW}, without
              regard to its conflict-of-law rules. Because the Service involves no
              real money or value, this clause concerns only the use of the game
              itself.
            </p>
          </LegalSection>
        )}

        <LegalSection title={GOVERNING_LAW ? "12. Contact" : "11. Contact"}>
          <p>
            Questions about these Terms? Reach out through the project&rsquo;s
            repository:{" "}
            <a href={API_REPO} target="_blank" rel="noopener noreferrer">
              github.com/zidanejidan12/OsuStocks.API
            </a>
            .
          </p>
          {CONTACT_EMAIL && (
            <p>
              You can also email us at{" "}
              <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
            </p>
          )}
        </LegalSection>
      </div>
    </div>
  );
}
